language: php
php:
  - 5.5
  - 5.4
  - 5.3

before_script:
  - composer self-update
  - composer install --dev

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml

after_script:
  - php vendor/bin/coveralls -v
